"""empty message

Revision ID: 25e946bc7704
Revises: 
Create Date: 2024-08-09 22:29:17.367107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25e946bc7704'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('user_name')

    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('email_id', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('user_name', ['user_name'], unique=True)

    op.create_table('reminder',
    sa.Column('reminder_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('component_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='reminder_ibfk_1'),
    sa.PrimaryKeyConstraint('reminder_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
