"""empty message

Revision ID: 408934171b67
Revises: 25e946bc7704
Create Date: 2024-08-09 22:30:45.301314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408934171b67'
down_revision = '25e946bc7704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=50), nullable=True),
    sa.Column('email_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('reminder',
    sa.Column('reminder_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_name', sa.String(length=50), nullable=False),
    sa.Column('component_name', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('reminder_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder')
    op.drop_table('user')
    # ### end Alembic commands ###
