"""empty message

Revision ID: f3a8bec66e0c
Revises: f65d4f099792
Create Date: 2024-08-09 22:31:43.376302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3a8bec66e0c'
down_revision = 'f65d4f099792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
